export QUARTUS_ROOTDIR=/opt/intelFPGA_pro/19.4/quartus
export QUARTUS_ROOTDIR_OVERRIDE=/opt/intelFPGA_pro/19.4/quartus
export INTELFPGAOCLSDKROOT=/opt/intelFPGA_pro/19.4/hld
export LD_LIBRARY_PATH=$INTELFPGAOCLSDKROOT/linux64/lib:$INTELFPGAOCLSDKROOT/host/linux64/lib:$INTELFPGAOCLSDKROOT/board/a10_ref/linux64/lib
export PATH=$PATH:$INTELFPGAOCLSDKROOT/bin:$INTELFPGAOCLSDKROOT/host/linux64/bin:$QUARTUS_ROOTDIR/bin
export CL_CONTEXT_EMULATOR_DEVICE_INTELFPGA=1
export CL_CONTEXT_EMULATOR_DEVICE_ALTERA=1

module load rh/devtoolset/8

